groups:
- name: MongoDb
  rules:
  - alert:  MongoDBAlert
    expr: rate(mongodb_op_counters_total{type="query"}[10m]) > 0.15
    for: 5s
    labels:
      team: mongodb
    annotations:
      titulo: "Muitas consultas"
      descricao: "O {{ $labels.instance }} esta com muitas consultas"

- name: WebApi
  rules:
  - alert: WebApiMuitosAcessos
    expr: sum(rate(http_requests_received_total[1m])) > 1
    for: 30s
    labels:
      team: webapi
    annotations:
      titulo: "Numero alto de acesso"
      descricao: "{{ $labels.instance }} esta com nomero alto de acessos ({{ $value }}s)"