kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
  
#kind create cluster --name kind-multi-nodes --image kindest/node:v1.26.0 --config .\cluster-one-control-plane.yaml