apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myexe
  template:
    metadata:
      labels:
        app: myexe
    spec:
      containers:
      - name: myconteiner
        image: kubedevio/nginx-color:green
        
