apiVersion: v1
kind: Pod
metadata:
  name: mypodblue
  labels:
    app: nginx
    name: blue
spec:
  containers:
  - name: mycontainer
    image: kubedevio/nginx-color:blue
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    # ports:
    #   - containerPort: 8080:80
