apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9216"
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        resources:
            requests:
              cpu: "1000m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
        envFrom:
          - secretRef:
              name: secret-mongo
      - name: mongodbexporter
        image: fabricioveronez/mongo_exporter
        resources:  {}
        ports:
          - containerPort: 9216
        env: 
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwdsreops@localhost:27017
         
